---
# https://www.home-assistant.io/components/google_assistant/#configuration
# If changing entities then, when finished:
#  1. Restart Home Assistant and:
#  2. Open the Google Home app to: Settings > More Settings > Assistant > Home Control.
#  3. Hit the + FAB and unlink the "[test] Home" app.
#  4. In a browser, head to https://console.actions.google.com and select your app
#  5. Open the "Simulator" on the left and start it (if not started)
#  6. Add back the "[test] Home" app like in #3 (might have wait/back out/refresh)
google_assistant:
  project_id: !secret google_assistant_project_id
  service_account:
    private_key: !secret google_assistant_service_account_private_key
    client_email: !secret google_assistant_service_account_client_email
  expose_by_default: false
  entity_config:
    script.goodnight:
      name: Goodnight
      expose: true

    light.basement_table_lamp:
      expose: true
      room: Basement
    light.basement_tv_led_strip:
      expose: true
      room: Basement
    light.basement_reading_lamp:
      expose: true
      room: Basement

    light.living_room_lamps:
      expose: true
      room: Living Room
    light.bookcase_left_lamp:
      name: Bookcase Left Lamp
      expose: true
      room: Living Room
      aliases:
        - Bookcase Left Lamp
        - bookcase left
        - bookcase left light
        - left bookcase lamp
        - left bookcase light
        - left bookcase
    light.bookcase_right_lamp:
      name: Bookcase Right Lamp
      expose: true
      room: Living Room
      aliases:
        - Bookcase Right Lamp
        - bookcase right
        - bookcase right light
        - right bookcase lamp
        - right bookcase light
        - right bookcase
    light.side_table_lamp:
      name: Side Table Lamp
      expose: true
      room: Living Room
      aliases:
        - Side Table Lamp
        - side table light
        - side table

    light.side_table_trees:
      name: Side Table Trees
      expose: true
      room: Living Room
