---
# The http component serves all files and data required for the
# Home Assistant frontend.
#
# https://www.home-assistant.io/components/http/
#
http:
  base_url: !secret http_base_url
  use_x_forwarded_for: true # This is so traefik we will see the real ip, output it to the logs, which fail2ban looks at to ban ips.
  trusted_proxies: !secret http_trusted_proxies