
---
# I store a lot of sensor data into InfluxDB, which allows me to query
# a longer history with ease. I use the Community Hass.io add-on for this,
# combined with the Community Hass.io Grafana add-on for the graphs.
#
# https://github.com/hassio-addons/addon-influxdb
# https://github.com/hassio-addons/addon-grafana
# https://www.home-assistant.io/components/influxdb/
#
influxdb:
  host: !secret influxdb_host
  port: !secret influxdb_port
  username: !secret influxdb_username
  password: !secret influxdb_password
  database: homeassistant
  max_retries: 10
  default_measurement: state
  include:
    entities:
      - sensor.master_bedroom_thermostat_humidity
      - sensor.master_bedroom_thermostat_temperature
      - sensor.basement_thermostat_temperature
      - sensor.basement_thermostat_humidity
      - sensor.speedtest_download
      - sensor.redfin_estimate
      - sensor.zestimate
  component_config_glob:
    sensor.*humidity:
      override_measurement: humidity
    sensor.*temperature:
      override_measurement: temperature