---
# The recorder component is storing details in a database which
# then are handled by the history component.
#
# https://www.home-assistant.io/components/recorder/
#
recorder:
  purge_keep_days: 7
  purge_interval: 1
