---
# The speedtestdotnet integration uses the Speedtest.net
# web service to measure network bandwidth performance.
#
# https://www.home-assistant.io/components/speedtestdotnet/
#
speedtestdotnet:
  scan_interval:
    hours: 2
  monitored_conditions:
    - ping
    - download
    - upload