---
# Brightens the living room lights and keeps them there flipping the automate
# lights input boolean off.
#
brighten_living_room_lights:
  sequence:
    - service: script.turn_off_automate_living_room_lights
    - service: light.turn_on
      data_template:
        entity_id: light.living_room_lamps
        # Note: Max range of Sylvania RGB bulbs is 689 (redest) to 152 (coldest)
        color_temp: 438
        brightness: 255
        transition: '2'
