
living_room_lamps_random_color:
  alias: Bookcase Lights Random Color
  sequence:
    - service: light.turn_on
      data_template:
        entity_id: 'light.living_room_lamps'
        rgb_color:
          - '{{range(256)|random}}'
          - '{{range(256)|random}}'
          - '{{range(256)|random}}'
        transition: '1'