alias: 'Say hello when alarm is disarmed'
trigger:
  - entity_id: alarm_control_panel.home
    platform: state
    from: armed_away
    to: disarmed
action:
  - service: tts.google_say
    entity_id: media_player.googlehome1686
    data:
      message: 'Welcome home.'