alias: On alarm armed set hvac to eco
trigger:
  - entity_id: alarm_control_panel.home
    platform: state
    to: armed_away
condition: []
action:
  - service: script.turn_on
    entity_id: script.set_nest_away
  - service: light.turn_off
    entity_id: light.living_room_lamps
  #- service: media_player.turn_off
  #  entity_id: media_player.frame_tv