
alias: Query MQTT on Startup
trigger:
  - platform: homeassistant
    event: start
action:
  - service: mqtt.publish
    data:
      topic: "cmnd/sonoffs/POWER"
  - service: mqtt.publish
    data:
      topic: "cmnd/sonoffs/POWER1"
  - service: mqtt.publish
    data:
      topic: "cmnd/sonoffs/POWER2"
  - service: mqtt.publish
    data:
      topic: "cmnd/sonoffs/POWER3"
