---
# Some fake secrets, or real. Probably fake, though.
# Here in case something gets nuked, I have a backup of all the secrets the rest
# of the system expects.
#
cert_domain: secret.com
http_base_url: home-assistant.secret.com

zone_home_elevation: 1
hass_latitude: 12.2345
hass_longitude: 12.2345
hass_time_zone: Secret/Timezone

nest_client_id: secret
nest_client_secret: secret

hass_configurator_url: http://secret:1111

ifttt_key: secret

# No need for Tuya with Tasmota on our switches
# tuya_username: secret
# tuya_password: secret

duckdns_domain: secret
duckdns_access_token: secret

google_assistant_project_id: secret
google_assistant_api_key: secret

mqtt_broker: 111.222.33.4
mqtt_username: secret
mqtt_password: secret

dark_sky_api_key: secret

zillow_zwsid: secret
zillow_zpid: secret

redfin_estimate_url: https://www.redfin.com/secret

simplisafe_username: secret
simplisafe_password: secret
simplisafe_code: 12345  # "12345"? That's amazing! I've got the same combination
                        # on my luggage.

github_hacs_token: secret

influxdb_host: 111.222.33.4
influxdb_port: 1234
influxdb_username: secret
influxdb_password: secret

http_trusted_proxies:
  - 111.22.33.0/24
  - 111.22.44.0/24

airthings_mac: "11:22:33:44:55:66"