---
# https://www.home-assistant.io/components/switch.mqtt/
# https://github.com/arendst/Sonoff-Tasmota/wiki/MQTT-Overview
#
# Currently mapped to light.basement_reading_lamp in ../lights
#
platform: mqtt
name: iselector-3004
state_topic: "stat/iselector-3004/POWER"
command_topic: "cmnd/iselector-3004/POWER"
availability_topic: "tele/iselector-3004/LWT"
payload_available: "Online"
payload_not_available: "Offline"
