---
# https://www.home-assistant.io/components/switch.mqtt/
# https://github.com/arendst/Sonoff-Tasmota/wiki/MQTT-Overview
#
# Currently, the modem
#
platform: mqtt
name: Modem # iselector-3001
icon: mdi:wan
state_topic: "stat/iselector-3001/POWER"
command_topic: "cmnd/iselector-3001/POWER"
availability_topic: "tele/iselector-3001/LWT"
payload_available: "Online"
payload_not_available: "Offline"