---
# https://www.home-assistant.io/components/switch.mqtt/
# https://github.com/arendst/Sonoff-Tasmota/wiki/MQTT-Overview
#
platform: mqtt
name: kmc4_30608_1001_01
state_topic: "stat/kmc4-30608-1001/POWER1"
state_on: "ON"
state_off: "OFF"
command_topic: "cmnd/kmc4-30608-1001/POWER1"
payload_on: "ON"
payload_off: "OFF"
availability_topic: "tele/kmc4-30608-1001/LWT"
payload_available: "Online"
payload_not_available: "Offline"
