---
# This wraps one of the switches with this named one allowing me to swap outlets
# or plugs from just here, instead of throughout the system.
#
platform: template
switches:
  modem:
    value_template: "{{ is_state('switch.kmc4_30608_1001_01', 'on') }}"
    turn_on:
      service: switch.turn_on
      data:
        entity_id: switch.kmc4_30608_1001_01
    turn_off:
      service: switch.turn_off
      data:
        entity_id: switch.kmc4_30608_1001_01