---
# Checks the cert expiration for a domain.
# Right now, my registrar doesn't do DN challenge for Let's Encrypt,
# so I have to manually update it every 90 days. This let's me monitor
# the expiration.
#
# https://www.home-assistant.io/components/cert_expiry/
#
platform: cert_expiry
host: !secret cert_domain