---
# https://www.home-assistant.io/components/sensor.mqtt/
#
platform: mqtt
name: kmc4_30608_1001_energy_total
state_topic: "tele/kmc4-30608-1001/SENSOR"
value_template: "{{ value_json['ENERGY']['Total'] }}"
unit_of_measurement: "kWh"
availability_topic: "tele/kmc4-30608-1001/LWT"
payload_available: "Online"
payload_not_available: "Offline"