---
# Outputs the public IP of Home Assistant.
#
# https://www.home-assistant.io/integrations/recollect_waste/
#
platform: recollect_waste
place_id: !secret recollect_waste_place_id
service_id: !secret recollect_waste_service_id