---
#
# https://www.home-assistant.io/components/template/
#
platform: template
sensors:
  homelab_power:
    value_template: "{{ states('sensor.kmc4_30608_1001_energy_power') }}"
    unit_of_measurement: "W"
