---
#
# https://www.home-assistant.io/components/template/
#
platform: template
sensors:
  dehumidifier_energy_yesterday:
    value_template: "{{ states('sensor.kmc4_30608_1002_energy_yesterday') }}"
    unit_of_measurement: 'kWh'